Added name Abidali
CMPT-2276-001-Douglas-College/hw1-Phuong-Matthew-Abidali pull request #3
Opened 2023-02-06 10:17 UTC by abiddouglas

2023-02-07 07:11 UTC, Mdavies-76 approved these changes

2023-02-07 20:33 UTC, LostCauseSauce requested changes
I just approved Matthew's name addition so there's conflict. I think you gotta put your name on the fifth line.

2023-02-07 21:45 UTC, Mdavies-76 approved these changes

2023-02-08 02:58 UTC, LostCauseSauce approved these changes
Looks good.

2023-02-08 02:58 UTC, merged