added hamilton algorithm
CMPT-2276-001-Douglas-College/hw1-Phuong-Matthew-Abidali pull request #32
Opened 2023-02-08 23:07 UTC by Mdavies-76

Added hamilton algorithm but requires reading from a file and the project solution (.sln) is not opening

2023-02-09 03:22 UTC, LostCauseSauce requested changes
I think you should make the hamilton algorithm its own function, that takes pair<vector<string>, vector<int>> as input and outputs also pair<vector<string>, vector<int>>.

2023-02-09 03:50 UTC, abiddouglas commented
Pair of vectors is not good idea for iteration. Vector of pairs is better. Just cleaning code into functions should do.

2023-02-09 22:47 UTC, abiddouglas approved these changes

2023-02-10 09:05 UTC, closed without merging

2023-02-10 09:08 UTC, abiddouglas commented
The feature is added to another branch and this branch is now obsolete.